//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimisComplaints.DataLayer
{
    using System;
    using System.Collections.Generic;
    using TimisComplaints.DataLayer.Interfaces;
    
    public partial class Letter : IEntity
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
